name: Publish Region Lambdas for NYS

on:
  push:
    branches:
      - nys

jobs:
  publish-nys:
    if: github.repository_owner == 'project-vagabond'
    name: Publish region specific lambdas for NYS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.13.1'

    - name: Install app dependencies
      run: npm install

    - name: Package lambdas
      run: |
        npm run artifact:create

    - name: Publish lambda package
      run: |
        aws s3 cp lambda.zip s3://${{ secrets.BUCKET_LAMBDAS }}/region-lambdas-${{ github.sha }}.zip
        echo "::set-output name=bundle::s3://${{ secrets.BUCKET_LAMBDAS }}/region-lambdas-${{ github.sha }}.zip"
